--carga de dados das tabelas auxiliares
INSERT INTO public.dias(cod,descricao) VALUES ('1','sábado')
INSERT INTO public.dias(cod,descricao) VALUES ('2','domingo')
INSERT INTO public.dias(cod,descricao) VALUES ('3','segunda-feira')
INSERT INTO public.dias(cod,descricao) VALUES ('4','terça-feira')
INSERT INTO public.dias(cod,descricao) VALUES ('5','quarta-feira')
INSERT INTO public.dias(cod,descricao) VALUES ('6','quinta-feira')
INSERT INTO public.dias(cod,descricao) VALUES ('7','sexta-feira')
INSERT INTO public.estados(cod,descricao) VALUES ('1','PI')
INSERT INTO public.estados(cod,descricao) VALUES ('2','PR')
INSERT INTO public.estados(cod,descricao) VALUES ('3','MS')
INSERT INTO public.estados(cod,descricao) VALUES ('4','RJ')
INSERT INTO public.estados(cod,descricao) VALUES ('5','MG')
INSERT INTO public.estados(cod,descricao) VALUES ('6','PB')
INSERT INTO public.estados(cod,descricao) VALUES ('7','SC')
INSERT INTO public.estados(cod,descricao) VALUES ('8','CE')
INSERT INTO public.estados(cod,descricao) VALUES ('9','MT')
INSERT INTO public.estados(cod,descricao) VALUES ('10','PE')
INSERT INTO public.estados(cod,descricao) VALUES ('11','BA')
INSERT INTO public.estados(cod,descricao) VALUES ('12','GO')
INSERT INTO public.estados(cod,descricao) VALUES ('13','SP')
INSERT INTO public.estados(cod,descricao) VALUES ('14','DF')
INSERT INTO public.estados(cod,descricao) VALUES ('15','RS')
INSERT INTO public.estados(cod,descricao) VALUES ('16','ES')
INSERT INTO public.estados(cod,descricao) VALUES ('17','RR')
INSERT INTO public.estados(cod,descricao) VALUES ('18','PA')
INSERT INTO public.estados(cod,descricao) VALUES ('19','RN')
INSERT INTO public.estados(cod,descricao) VALUES ('20','MA')
INSERT INTO public.estados(cod,descricao) VALUES ('21','AL')
INSERT INTO public.estados(cod,descricao) VALUES ('22','SE')
INSERT INTO public.estados(cod,descricao) VALUES ('23','RO')
INSERT INTO public.estados(cod,descricao) VALUES ('24','TO')
INSERT INTO public.estados(cod,descricao) VALUES ('25','AP')
INSERT INTO public.estados(cod,descricao) VALUES ('26','AM')
INSERT INTO public.estados(cod,descricao) VALUES ('27','AC')
INSERT INTO public.causas(cod,descricao) VALUES ('1','Ingestão de álcool pelo condutor')
INSERT INTO public.causas(cod,descricao) VALUES ('2','Condutor deixou de manter distância do veículo da frente')
INSERT INTO public.causas(cod,descricao) VALUES ('3','Reação tardia ou ineficiente do condutor')
INSERT INTO public.causas(cod,descricao) VALUES ('4','Acumulo de água sobre o pavimento')
INSERT INTO public.causas(cod,descricao) VALUES ('5','Mal súbito do condutor')
INSERT INTO public.causas(cod,descricao) VALUES ('6','Chuva')
INSERT INTO public.causas(cod,descricao) VALUES ('7','Ausência de reação do condutor')
INSERT INTO public.causas(cod,descricao) VALUES ('8','Manobra de mudança de faixa')
INSERT INTO public.causas(cod,descricao) VALUES ('9','Pista Escorregadia')
INSERT INTO public.causas(cod,descricao) VALUES ('10','Ausência de sinalização')
INSERT INTO public.causas(cod,descricao) VALUES ('11','Condutor Dormindo')
INSERT INTO public.causas(cod,descricao) VALUES ('12','Velocidade Incompatível')
INSERT INTO public.causas(cod,descricao) VALUES ('13','Acessar a via sem observar a presença dos outros veículos')
INSERT INTO public.causas(cod,descricao) VALUES ('14','Conversão proibida')
INSERT INTO public.causas(cod,descricao) VALUES ('15','Transitar na contramão')
INSERT INTO public.causas(cod,descricao) VALUES ('16','Ultrapassagem Indevida')
INSERT INTO public.causas(cod,descricao) VALUES ('17','Desrespeitar a preferência no cruzamento')
INSERT INTO public.causas(cod,descricao) VALUES ('18','Acostamento em desnível')
INSERT INTO public.causas(cod,descricao) VALUES ('19','Demais falhas mecânicas ou elétricas')
INSERT INTO public.causas(cod,descricao) VALUES ('20','Carga excessiva e/ou mal acondicionada')
INSERT INTO public.causas(cod,descricao) VALUES ('21','Problema com o freio')
INSERT INTO public.causas(cod,descricao) VALUES ('22','Ingestão de álcool e/ou substâncias psicoativas pelo pedestre')
INSERT INTO public.causas(cod,descricao) VALUES ('23','Curva acentuada')
INSERT INTO public.causas(cod,descricao) VALUES ('24','Estacionar ou parar em local proibido')
INSERT INTO public.causas(cod,descricao) VALUES ('25','Avarias e/ou desgaste excessivo no pneu')
INSERT INTO public.causas(cod,descricao) VALUES ('26','Pedestre cruzava a pista fora da faixa')
INSERT INTO public.causas(cod,descricao) VALUES ('27','Obstrução na via')
INSERT INTO public.causas(cod,descricao) VALUES ('28','Acesso irregular')
INSERT INTO public.causas(cod,descricao) VALUES ('29','Pista esburacada')
INSERT INTO public.causas(cod,descricao) VALUES ('30','Animais na Pista')
INSERT INTO public.causas(cod,descricao) VALUES ('31','Falta de acostamento')
INSERT INTO public.causas(cod,descricao) VALUES ('32','Entrada inopinada do pedestre')
INSERT INTO public.causas(cod,descricao) VALUES ('33','Acumulo de areia ou detritos sobre o pavimento')
INSERT INTO public.causas(cod,descricao) VALUES ('34','Pedestre andava na pista')
INSERT INTO public.causas(cod,descricao) VALUES ('35','Desvio temporário')
INSERT INTO public.causas(cod,descricao) VALUES ('36','Transitar no acostamento')
INSERT INTO public.causas(cod,descricao) VALUES ('37','Problema na suspensão')
INSERT INTO public.causas(cod,descricao) VALUES ('38','Objeto estático sobre o leito carroçável')
INSERT INTO public.causas(cod,descricao) VALUES ('39','Deficiência do Sistema de Iluminação/Sinalização')
INSERT INTO public.causas(cod,descricao) VALUES ('40','Trafegar com motocicleta (ou similar) entre as faixas')
INSERT INTO public.causas(cod,descricao) VALUES ('41','Condutor usando celular')
INSERT INTO public.causas(cod,descricao) VALUES ('42','Restrição de visibilidade em curvas horizontais')
INSERT INTO public.causas(cod,descricao) VALUES ('43','Ingestão de álcool ou de substâncias psicoativas pelo pedestre')
INSERT INTO public.causas(cod,descricao) VALUES ('44','Declive acentuado')
INSERT INTO public.causas(cod,descricao) VALUES ('45','Frear bruscamente')
INSERT INTO public.causas(cod,descricao) VALUES ('46','Iluminação deficiente')
INSERT INTO public.causas(cod,descricao) VALUES ('47','Área urbana sem a presença de local apropriado para a travessia de pedestres')
INSERT INTO public.causas(cod,descricao) VALUES ('48','Demais Fenômenos da natureza')
INSERT INTO public.causas(cod,descricao) VALUES ('49','Demais falhas na via')
INSERT INTO public.causas(cod,descricao) VALUES ('50','Faixas de trânsito com largura insuficiente')
INSERT INTO public.causas(cod,descricao) VALUES ('51','Obras na pista')
INSERT INTO public.causas(cod,descricao) VALUES ('52','Retorno proibido')
INSERT INTO public.causas(cod,descricao) VALUES ('53','Afundamento ou ondulação no pavimento')
INSERT INTO public.causas(cod,descricao) VALUES ('54','Falta de elemento de contenção que evite a saída do leito carroçável')
INSERT INTO public.causas(cod,descricao) VALUES ('55','Ingestão de substâncias psicoativas pelo condutor')
INSERT INTO public.causas(cod,descricao) VALUES ('56','Neblina')
INSERT INTO public.causas(cod,descricao) VALUES ('57','Condutor desrespeitou a iluminação vermelha do semáforo')
INSERT INTO public.causas(cod,descricao) VALUES ('58','Sistema de drenagem ineficiente')
INSERT INTO public.causas(cod,descricao) VALUES ('59','Acumulo de óleo sobre o pavimento')
INSERT INTO public.causas(cod,descricao) VALUES ('60','Sinalização mal posicionada')
INSERT INTO public.causas(cod,descricao) VALUES ('61','Pista em desnível')
INSERT INTO public.causas(cod,descricao) VALUES ('62','Transitar na calçada')
INSERT INTO public.causas(cod,descricao) VALUES ('63','Fumaça')
INSERT INTO public.causas(cod,descricao) VALUES ('64','Redutor de velocidade em desacordo')
INSERT INTO public.causas(cod,descricao) VALUES ('65','Deixar de acionar o farol da motocicleta (ou similar)')
INSERT INTO public.causas(cod,descricao) VALUES ('66','Restrição de visibilidade em curvas verticais')
INSERT INTO public.causas(cod,descricao) VALUES ('67','Semáforo com defeito')
INSERT INTO public.causas(cod,descricao) VALUES ('68','Faróis desregulados')
INSERT INTO public.causas(cod,descricao) VALUES ('69','Modificação proibida')
INSERT INTO public.causas(cod,descricao) VALUES ('70','Participar de racha')
INSERT INTO public.causas(cod,descricao) VALUES ('71','Sinalização encoberta')
INSERT INTO public.tipos(cod,descricao) VALUES ('1','Colisão traseira')
INSERT INTO public.tipos(cod,descricao) VALUES ('2','Tombamento')
INSERT INTO public.tipos(cod,descricao) VALUES ('3','Colisão frontal')
INSERT INTO public.tipos(cod,descricao) VALUES ('4','Saída de leito carroçável')
INSERT INTO public.tipos(cod,descricao) VALUES ('5','Colisão com objeto')
INSERT INTO public.tipos(cod,descricao) VALUES ('6','Colisão lateral mesmo sentido')
INSERT INTO public.tipos(cod,descricao) VALUES ('7','Engavetamento')
INSERT INTO public.tipos(cod,descricao) VALUES ('8','Colisão lateral sentido oposto')
INSERT INTO public.tipos(cod,descricao) VALUES ('9','Colisão transversal')
INSERT INTO public.tipos(cod,descricao) VALUES ('10','Capotamento')
INSERT INTO public.tipos(cod,descricao) VALUES ('11','Queda de ocupante de veículo')
INSERT INTO public.tipos(cod,descricao) VALUES ('12','Incêndio')
INSERT INTO public.tipos(cod,descricao) VALUES ('13','Derramamento de carga')
INSERT INTO public.tipos(cod,descricao) VALUES ('14','Atropelamento de Pedestre')
INSERT INTO public.tipos(cod,descricao) VALUES ('15','Eventos atípicos')
INSERT INTO public.tipos(cod,descricao) VALUES ('16','Atropelamento de Animal')
INSERT INTO public.classificacoes(cod,descricao) VALUES ('1','Com Vítimas Feridas')
INSERT INTO public.classificacoes(cod,descricao) VALUES ('2','Com Vítimas Fatais')
INSERT INTO public.classificacoes(cod,descricao) VALUES ('3','Sem Vítimas')
INSERT INTO public.condicoes(cod,descricao) VALUES ('1','Nublado')
INSERT INTO public.condicoes(cod,descricao) VALUES ('2','Céu Claro')
INSERT INTO public.condicoes(cod,descricao) VALUES ('3','Chuva')
INSERT INTO public.condicoes(cod,descricao) VALUES ('4','Garoa/Chuvisco')
INSERT INTO public.condicoes(cod,descricao) VALUES ('5','Sol')
INSERT INTO public.condicoes(cod,descricao) VALUES ('6','Ignorado')
INSERT INTO public.condicoes(cod,descricao) VALUES ('7','Nevoeiro/Neblina')
INSERT INTO public.condicoes(cod,descricao) VALUES ('8','Vento')
INSERT INTO public.condicoes(cod,descricao) VALUES ('9','Granizo')
INSERT INTO public.condicoes(cod,descricao) VALUES ('10','Neve')